#+title: Manual installation procedure

This package has a strong dependency on =python3=. The installation of
the right version of python is up to you.

You first need to clone this repository. We recommend you to put it
somewhere under your =.emacs.d= folder.

#+begin_src emacs-lisp
cd ~/.emacs.d
git clone https://git.deparis.io/flycheck-grammalecte
#+end_src

On GNU/Linux and Mac OS, you can benefit of a =Makefile=, which will
download for you the last version of Grammalecte and compile the GNU
Emacs Lisp package. For that to happen, go to the newly created
=flycheck-grammalecte= folder and enter the ~make~ command.

#+begin_src
cd flycheck-grammalecte
make
#+end_src

When it's done, you can add the following line in your GNU Emacs config
file:

#+begin_src emacs-lisp
(load-file "~/.emacs.d/flycheck-grammalecte/flycheck-grammalecte.elc")
#+end_src

And everything should be fine.

You may want to clean up a bit the Flycheck-grammalecte directory by
entering the following command: ~make clean~.

If you cannot or don't want to use the =Makefile=, you can also just add
the following line to your GNU Emacs config file (please note that in
that case, we call the =.el= file as we have not byte-compiled it):

#+begin_src emacs-lisp
(load-file "~/.emacs.d/flycheck-grammalecte/flycheck-grammalecte.el")
#+end_src

Then restart GNU Emacs.

The last expected step is to download the [[https://grammalecte.net/#download][CLI & Server upstream package]].
Just enter the following command:
~M-x flycheck-grammalecte-download-grammalecte~
